### ISSUE TITLE
Downloading images suitable Testing 

### ISSUE THREAD

**Issue by lewismcnish** [OirthirSAT/image-processing-pipeline#19]
## Overview

Download ~50 images for testing all python scripts, they can be found from Sentinel or Landsat data and upload to the Teams OneDrive and Github using large file storage try to get a good mixture including some with cloud (Partial/full coverage), no coastline (for a worst case), complex coastline (Scottish Isles?), snow coverage? ensure all are of UK region. Must be .tif files, must contain RGB and NIR colour bands, ideally sampled at GSD of 30m.

For help downloading images if struggling Contact Kangyong Zhang on Teams

## Requirements

1. Download images
2. Are .tif Files
3. Contains RGB and NIR colour bands
4. Variety of landscape
5. Sampled at GSD of 30m
6. Are of the UK region

## Definition of Done

1. Files are stored on OneDrive and Github LFS
2. Files can be downloaded easily
3. Ability to open and preview files using typical preview software of OS

## Resources
Sentinel Info on data
https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel2.html

LandSat info on data
https://landsat.gsfc.nasa.gov/data/data-access/

Github LFS
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage

GSD: Ground sample distance

**Comment by JazzyMaxine** [comment]
Looking at the Landsat 8-9 OLI/TIRS C2 L2 dataset (chatGPT said this one had all the features you're looking for) on https://earthexplorer.usgs.gov/, the downloads are 27 files: 13 Level-2 Surface Reflectance Bands and 14 Level-2 Surface Temperature Bands. The reflectance bands contain 7 bands as .TIF files, a QA_AEROSOL.TIF, QA_PIXEL.TIF, and a QA_RADSAT.TIF. Finally three non-.TIF files: ANG.txt, MTL.txt, and MTL.xml. Which of these files should I be downloading? Am I in the right dataset?
