### ISSUE TITLE
Add Aberdeenshire.TIF to marching-squares/

### ISSUE THREAD

**Issue by JazzyMaxine** [OirthirSAT/image-processing-pipeline#25]
## Overview

It's a dependency for marching-squares/marching-squares.ipynb.

## Requirements

1. Add the file.

## Definition of Done

1. Aberdeenshire.TIF exists in the marching-squares directory.
2. Marching-squares/marching-squares.ipynb works on a fresh clone of the repository, or a new issue has been created with any new bugs that appear after fixing this one.

**Comment by lewismcnish** [comment]
If this is done ensure the use of Github LFS, this file should not be pushed straight to Github Due to large size ~300Mb

**Comment by JazzyMaxine** [comment]
> If this is done ensure the use of Github LFS, this file should not be pushed straight to Github Due to large size ~300Mb

I wasn't aware of the file size, should we talk about this next week? I'm unfamiliar with Github LFS so can't offer any help but if someone knows how it works and is willing to implement it then feel free.

**Comment by lewismcnish** [comment]
happy to discuss next week, I Haven't worked with LFS before either, for the time being it is easier if everyone obtains their own copy of Aberdeenshire.tif from the teams and downloads a local copy, obviously not ideal but works for now
