### ISSUE TITLE
Discuss refactoring marching_squares/marching_squares.py to rely less on object state.

### ISSUE THREAD

**Issue by JazzyMaxine** [OirthirSAT/image-processing-pipeline#34]
## Overview

The functions in `MarchingSquares` currently form the following dependency graph:
![MarchingSquares_function_graph drawio](https://github.com/user-attachments/assets/31533ecd-d795-4649-a439-ed92871f0b1a)

This is unnecessarily complicated given many of the functions could be trivially refactored to be pure, making the flow easier to understand, less coupled, and less prone to error. This is evidenced by how many functions take as input exactly the output of the function which was called earlier: readfile, otsu_segmentation, vector shapes, show_coastline... 

As a rule of thumb, instance variables represent *object state*, higher level ideas that reflect the object as a whole and not necessarily implementation details of the individual functions. E.G. a video game character object might have "sprite" and "position" instance variables, but it wouldn't have an "angles_to_enemies" instance variable if that were the intermediate state of a function that calculates whether a shot the player makes hits an enemy. This is comparable to our result_image or vectors instance variables, which are each returned by a private function and are only intermediate steps in the actual calculation that the API is providing: calculating the coastline vectors.

I'm opening this issue to discuss potential refactorings of the MarchingSquares class, and provide two options for consideration. I appreciate all comments and opinions on which if any refactoring is preferrable. I have assigned the issue to everyone I could find in the Oirthir Software teams channel, but if I'm missing someone feel free to add them.

## Option A

All instance variables except the following will be removed, and the functions getting them as input or setting them as output will simply accept them as parameters and return them. The run script will be slightly altered to handle this. Instance variables to be kept:
1. self.filename, self.downsample_factor, and self.image represent the initial state of the object.
2. self.shapes represents the final output of a MarchingSquares object, and thus makes sense to be an instance variable.

## Option B

You'll notice that in option A only the input and output of the object are kept as state. That's because the marching squares script doesn't map well onto OOP, and really represents a single function rather than an object (we're not going to be initialising multiple MarchingSquares, it's really just a data in -> data out function we want to call as part of our pipeline). This is a common problem in C++ and Java, which require everything to be an object, and these cases are usually handled by creating static functions. i.e. `output = MarchingSquares.run(parameters)` in one step using a static `run` function, as we don't actually need to keep hold of a MarchingSquares object, similar to `Math.abs()` or any `main()` function. We would still have our other private helper functions, but none of them would interface with instance variables, and main would simply take a filename and resize factor and then return the coastline vectors. 

## Definition of Done

This issue will be closed when we have decided the following:
1. Whether to refactor marching_squares.py
2. If yes to 1., how to refactor it

If we decide further action is needed, a new issue will be created WRT the actual implementation of these changes.

**Comment by JazzyMaxine** [comment]
I would prefer option 2, because I don't see any reason for the MarchingSquares object to contain any state at all. From my understanding, it's a single function run in the pipeline and we'll be running it once per image on huge sets of images. It doesn't make sense to me to create a distinct object and keep it in memory for every single image, once it's processed it's processed and can wait patiently in storage for downlink; So if we're just creating an object for the duration of the processing and then destroying them it's an unnecessary abstraction that comes with (minor) time, memory, and power consumption overhead.

**Comment by lewismcnish** [comment]
@JazzyMaxine I believe we decided on option 2 in the meeting, could we get this started at some point either yourself or assign someone else :)
